DNA Data Visualization (DDV) software

This C# application creates visualizations of FASTA formatted DNA nucleotide data. 
DDV can download FASTA sequences from NIH, or use local FASTA formatted files. 
DDV generates a DeepZoomImage visualizations of DNA data.

The Python version of DDV was developed by Newline Technical Innovations and can be found at:
https://github.com/josiahseaman/DDV/tree/python-master

This project is a fork of the C# DDV developed at Concordia University:
http://www.photomedia.ca/DDV/

The above page is also available in the documentation folder of github:
https://github.com/photomedia/DDV/blob/master/documentation/download/index.html

DDV Licence:
https://github.com/photomedia/DDV/blob/master/DDV-license.txt

Examples (Demonstration):

Visualizations generated with DDV can be placed on a web server. 
The following contains the links to examples of the visualizations 
generated by Tomasz Neugebauer, Éric Bordeleau, Vincent Burrus and Ryszard Brzezinski 
with this software: DNA Data Visualizations Generated with DDV Software. 
These examples include a number of bacteria chromosomes, as well as the entire Homo Sapiens genome. 

http://www.photomedia.ca/DDV/dnadata/

The source code and image data for these generated examples is also available as a dataset at Zenodo 
http://dx.doi.org/10.5281/zenodo.33608


Installation instructions / Help page / FAQ:

http://www.photomedia.ca/DDV/download/index.html
The above page is also available in the documentation folder of github:
https://github.com/photomedia/DDV/blob/master/documentation/download/index.html


Compile Instructions

Windows:

  - Install Mercurial so it is properly on your path
  - Download PyWin32 from: http://sourceforge.net/projects/pywin32/files/pywin32/Build%20219/pywin32-219.win-amd64-py3.4.exe/download
  - Using the easy_install in your new Virtual Environment (/path/to/adsm_venv/Scripts/easy_install), install PyWin32:

        `easy_install pywin32-219.win-amd64-py3.4.exe`

  - Using /path/to/adsm_venv/Scripts/pip install cx_freeze:

        `pip install hg+https://bitbucket.org/BryanHurst/cx_freeze`

    > Note: this currently does not work; instead, install cx_freeze 4.3.4 using pip, then manually apply [this patch](https://bitbucket.org/BryanHurst/cx_freeze/commits/eba6cb644d390f69f07adbf9fdcead71ec0feebf?at=default) and [this patch](https://bitbucket.org/BryanHurst/cx_freeze/commits/22d73fe6386d92834339bdea30b3786a3543b2de?at=default) to the cx_freeze files that pip installed in your site-packages folder.


